name: Generate README.md

on:
  schedule:
    - cron: '0 */2 * * *' # 每两小时执行一次
  workflow_dispatch:  # 手动触发

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    env:
      TOKEN: ${{ secrets.TOKEN }}  # GitHub Personal Access Token，需要在仓库的 Secrets 中设置
    steps:
      - name: Checkout code
        with: 
          token: ${{ secrets.TOKEN }}
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Generate README.md
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
        run: |
          python scripts/generate_readme.py
      
      - name: Commit
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi
          
          git config --global user.name "bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "bot: 定期自动生成 markdown 文件"
          git push
